### ISSUE TITLE
BZ #127: Bucardo Fails to add table if db doesn't have password. Ignores pgpass file

### ISSUE THREAD

**Issue by machack666** [bucardo/bucardo#140] opened 2017-04-07 22:13 UTC
Chris 2014-01-19 13:46:41 EST
root@vipserver:/usr/local/src/dbixsafe# bucardo add tables
subscription_call_plan_prefixes subscription_call_plan_rates_base
subscription_call_plan_suppliers_rates_prefixes
DBD::Pg::st execute failed: ERROR:  DBI
connect('dbname=vip-consult.co.uk_portal','bucardo',...) failed: fe_sendauth:
no password supplied at line 62
CONTEXT:  PL/Perl function "validate_goat" at /usr/local/bin/bucardo line 4531.

root@vipserver:/usr/local/src/dbixsafe# bucardo list db
Database: fs1Slave      Status: active  Conn: psql -U root -d freeswitch -h
cctv.vip-consult.co.uk
Database: portalMaster  Status: active  Conn: psql -U bucardo -d
vip-consult.co.uk_portal

the pgpass is present and works if connected through psql:

root@vipserver:/usr/local/src/dbixsafe# psql -U root -d freeswitch -h
cctv.vip-consult.co.uk
psql (9.1.9, server 9.1.11)
SSL connection (cipher: DHE-RSA-AES256-SHA, bits: 256)
Type "help" for help.

freeswitch=#

**Comment by einhverfr** [comment] 2017-10-18 18:45
I have monkey-patched this in production.  The specific problem here is that we are forcing a password in, while it should be set to undef if no password found.

**Comment by phips28** [comment] 2018-02-28 06:53
@einhverfr 
any idea how to fix that?
I have my passwords in the .pgpass file.
can you help me please?

```
$ bucardo add table ocean_01.influencer db=waves_stag_old herd=waves_stag_old_group1 --verbose
DBD::Pg::st execute failed: ERROR:  DBI connect('dbname=staging_01;host=rds-postgres-staging-waves-001.czzypov38wfy.us-east-1.rds.amazonaws.com;port=5432','SwellIsWaving',...) failed: fe_sendauth: no password supplied at line 63.
CONTEXT:  PL/Perl function "validate_goat" at /usr/local/bin/bucardo line 5209.
```

The `add sequences` worked:
`bucardo add sequences ocean_01.global_id_sequence db=waves_stag_old herd=waves_stag_old_group1 --verbose`

**Comment by phips28** [comment] 2018-02-28 07:08
I added the password to the database `add db ...pass=xy` 
this works.

**Comment by jrnp97** [comment] 2019-02-28 04:45
I Tried and works for me.
`sudo PGPASSFILE=<path/to/.pgpass> bucardo add db <name> dbname=<db_name> user=bucardo host=127.0.0.1`

**Comment by changchichung** [comment] 2019-05-30 04:51
I have the same problem , I already modify pg_hba.conf like below
```
# Database administrative login by Unix domain socket
host	all	postgres	192.168.11.1/24	trust
local   all             postgres                                peer
host	all	bucardo	192.168.11.1/24	trust
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
# IPv6 local connections:
host    all             all             ::1/128                 md5
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     peer
host    replication     all             127.0.0.1/32            md5
host    replication     all             ::1/128                 md5
postgres@ubuntu:~$ 
```
and I can connect to psql using bucardo in shell
```
postgres@ubuntu:~$ psql -h 192.168.11.181 -U bucardo
psql (10.8 (Ubuntu 10.8-0ubuntu0.18.04.1))
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

bucardo=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 bucardo   | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres         +
           |          |          |             |             | postgres=CTc/postgres+
           |          |          |             |             | bucardo=CTc/postgres
 d1        | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(5 rows)

bucardo=# 
```

But I can not use bucardo command .
```
postgres@ubuntu:~$ bucardo show all
DBI connect('dbname=bucardo','bucardo',...) failed: FATAL:  Peer authentication failed for user "bucardo" at /usr/local/bin/bucardo line 310.
postgres@ubuntu:~$
```
any suggestions ?

**Comment by jonjensen** [comment] 2023-03-09 14:58
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.

**Closed by jonjensen** 2023-03-09 14:58 UTC

**Comment by dexios1** [comment] 2023-09-03 09:26
Hi, I have a similar issue as @changchichung. What other additional information can I share to help? I'm running bucardo 5.6.0

**Comment by sqk0232** [comment] 2024-09-14 12:27
提供一个解决方式:
bucardo -P 密码 命令
