### ISSUE TITLE
Bucardo 5.4.1 strict_checking=false not working

### ISSUE THREAD

**Issue by frosty5689** [bucardo/bucardo#163] opened 2018-03-15 18:29 UTC
Hi,

I am trying to use customcols to sync to another database but only select columns. I have tested customcols and it works to allow tables with missing columns to sync. But ran into a problem with MCP sync validation when bucardo first starts.

Here's the log

(3393) [Thu Mar 15 18:11:49 2018] MCP Warning: Source database for sync "test_sync" has column "test_user_id" of table "public.users", but target database "target_db" does not
(3393) [Thu Mar 15 18:11:49 2018] MCP Validation of sync test_sync FAILED
(3393) [Thu Mar 15 18:11:49 2018] MCP Active syncs: 0
(3393) [Thu Mar 15 18:11:49 2018] MCP Entering main loop

I have strict_checking=false set for the sync and all the tables.

I can verify sync still works if I temporarily add the column and drop it after the sync has started.

**Comment by dwardu89** [comment] 2018-03-16 14:51
As far as i know, that would work if you have `allowonetimecopy=2` What's the setup of your sync?

**Comment by nibohr** [comment] 2021-06-25 22:58
> I have tested customcols and it works to allow tables with missing columns to sync. 

I'm trying to achieve that but I´m stuck

**Comment by jonjensen** [comment] 2023-03-09 14:56
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.

**Closed by jonjensen** 2023-03-09 14:56 UTC

**Comment by nmcnew** [comment] 2025-09-04 16:19
Sorry Zombie-ing this issue. This is still an issue. Using bucardo 5.6.0 and setting customcols, during the validation of source to destination table schema, it does not check if there is a custom selection happening and errors because destination does not have the same columns as source. Ideally this would check if there is a customcol/customselect for the table it's validating _instead_ of just dying. The check happens in the following section. Also this should not be a warning since it causes the sync to stop.
https://github.com/bucardo/bucardo/blob/d9919c804d2c84a25e9bd8895908e80932609160/Bucardo.pm#L7208-L7214
