### ISSUE TITLE
Bucardo stuck after connection problems

### ISSUE THREAD

**Issue by gustavotonini** [bucardo/bucardo#153] opened 2017-08-08 14:53 UTC
Hi team,
We have a bucardo setup with 4 databases in multimaster mode. One of them goes offline frequently due to problems in an Internet link.

When this database comes back online after some minutes, bucardo continues with "Bad" status indefinitely and needs to be restarted (kicking the sync does not help too) to return to normal operation.

**Comment by dojodominator** [comment] 2017-08-29 15:13
I'm seeing the same thing in a multi-maser replication environment.  In the logs, I get the ling "VAC Warning! VAC was killed at line 7697: DBD::Pg::st execute failed: no connection to the server at /usr/local/share/perl5/Bucardo.pm line 7697"  At that point, it looks like the VAC process is dead, and no attempts are made to ever update the state of the database to 'ACTIVE' from 'STALLED'.  What is interesting is that this happens after 1 sync completes successfully between the 2 master databases.  After that line logs, no future syncs happen.

The root of the issue, as far as I can tell, is that the 'set status = active' only happens within the validate_sync (line 6709 and 6731) which is only run in activate_sync, which is only run from mcp_main (if the reload command was given) or from reload_mcp.

**Comment by dojodominator** [comment] 2017-08-29 15:15
I would recommend also setting the database (and sync) to active as part of the VAC loop which periodically attempts to connect on failed connections, or when the KID starts when the connection is reestablished.

**Comment by dojodominator** [comment] 2017-08-30 15:06
After more digging, I'm now thinking that the issue is that the NOTIFY trigger does not work after the connection is lost and restored.  Setting the 'expiretime' variable enables the sync to continue to work based on the timeout.

**Comment by gustavotonini** [comment] 2017-08-30 15:42
Expiretime? There is no reference to this variable in the code...

**Comment by dojodominator** [comment] 2017-08-30 16:30
sorry, "checktime" variable.

**Comment by gustavotonini** [comment] 2017-08-30 18:28
Theoretically, setting checktime variable would force a kick in the sync periodically. In my test case, kicking the sync manually does not work too. We also tried to execute a kick every 5 minutes using crontab.

**Comment by dojodominator** [comment] 2017-08-30 18:43
hmmm... "checktime" causes the sync to still work for me, even though the database and sync remain in the "stalled" state indefinitely.  I haven't figured out how to get the database and sync back into the active state without restarting bucardo.

**Comment by gustavotonini** [comment] 2017-08-30 18:45
How many seconds did you set on checktime? I will try it too

**Comment by dojodominator** [comment] 2017-08-30 19:36
30 seconds

**Comment by dojodominator** [comment] 2017-08-30 19:37
I don't think that {DB} ever has any values here: https://github.com/bucardo/bucardo/blob/5.4.1/Bucardo.pm#L1648

**Comment by dojodominator** [comment] 2017-08-30 20:29
Check out the branch I'm working for progress on this.  So far, I have the database and sync being remarked as active, and I'm just trying to figure out how to reconnect the NOTICE from the remote db.
https://github.com/bucardo/bucardo/compare/5.4.1...dojodominator:restore_syncs

**Comment by gustavotonini** [comment] 2017-08-30 22:57
My customer hired a better Internet provider, so the problem is not happening frequently. Otherwise I could test your patch there.

You may submit the PR to see the comments from core developers.

**Comment by gustavotonini** [comment] 2017-09-25 16:44
Even using a better Internet link, the problem happened again and I discovered some things:
1-bucardo status shows state "Begin txn..."
2-killing all bucardo sessions on all nodes makes bucardo to go back to life
3-There is an idle session on one of the nodes that has just executed "DBD::Pg::ping"

So I think the problem is related to ping check. The Internet link probably went down during ping check and the library is waiting indefinitely for a response. 

I will try to set the variable "statement_timeout" on postgresql.conf to see if it helps.

**Comment by jonjensen** [comment] 2023-03-09 14:57
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.

**Closed by jonjensen** 2023-03-09 14:57 UTC
