### ISSUE TITLE
Don't reconect after network down

### ISSUE THREAD

**Issue by brestows** [bucardo/bucardo#105] opened 2015-11-06 08:29 UTC
Hello, there is the following problem in bucardo operation: if the server with bucardo loses connection, then bucardo doesn’t restore the connection, it trys to do it but fails. Its operation restore only after I reboot bucardo service. Here http://hastebin.com/hanosaxoze.coffee are the full logs of bucardo’s operation before it’s lost the connection until I reboot it. Here http://hastebin.com/paquwogibe.vhdl is its configuration. Here http://hastebin.com/eborisagom.bash  is the script of launching bucardo for CentOS

**Comment by asierazaceta** [comment] 2016-04-14 13:44
Hi,
I've got a similar issue where, after the connection is lost, the sync si marked as 'active' but 'stalled' and it doesn't recover from that status when the connection is back. Then I've to deactivate, revalidate and activate the sync for it to come back.

This is quite critical for us as one of the masters is not always on, so we have to manually stop and start bucardo whenever it goes off/on-line to avoid the stalled sync issue

**Comment by mterrien** [comment] 2016-05-02 14:45
Hi, 

Do you have an update regarding this critical issue?
I upgraded from 5.3.1 to 5.4.1 thinking that it would solve this problem but it didn't.
It seems this problem exists since the start of release 5 and it has never been fixed.
bucardo revalidation + start/stop procedure is definitely not satisfying in production.

I upgraded from Bucardo 4 to 5 to solve the delta purge issue causing deadlocks at some point and database to grow. Now this  problem seems to be solved but this new one is as critical as the previous one.

**Comment by mterrien** [comment] 2016-05-02 16:54
I implemented the workaround for those interested.
I use bucardo with 2 servers and 2 different syncs (master/slave bucardo_source, master/master bucardo_latest).

Create a cronned task every 5 minutes for instance as below:
- /etc/cron.d/bucardoRestartIfStalled
```
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin
MAILTO=""
*/5 * * * * root /opt/myproject/setup/bucardoRestartIfStalled.sh
```

- /opt/myProject/bucardoRestartIfStalled.sh
```
#!/bin/bash
BUCARDO_RESTART_LOG=/opt/myproject/setup/bucardoRestart.log
NEEDS_RESTART=`psql -qAt -U postgres -d bucardo -c "select count(*) from bucardo.sync where status='stalled'" | tr -d [:space:]`;

if [ ! -e $BUCARDO_RESTART_LOG ] ;
then
        touch $BUCARDO_RESTART_LOG;
fi

if [ "$NEEDS_RESTART" != "0" ] ;
then
        bucardo deactivate all   | tee -a $BUCARDO_RESTART_LOG
        sleep 5
        bucardo validate all   | tee -a $BUCARDO_RESTART_LOG
        sleep 10
        bucardo activate all   | tee -a $BUCARDO_RESTART_LOG
        sleep 10
        bucardo kick all  | tee -a $BUCARDO_RESTART_LOG
        sleep 10
        bucardo stop   | tee -a $BUCARDO_RESTART_LOG
        sleep 10
        bucardo start   | tee -a $BUCARDO_RESTART_LOG
        sleep 10
        bucardo kick all
        sleep 10
fi

```

**Comment by oviwankenobi** [comment] 2017-05-09 09:42
I have encountered this situation
this command "bucardo status" shows me state "Bad"

yet this command
psql -qAt -U postgres -d bucardo -c "select count(*) from bucardo.sync where status!='active'" 

returns zero and shows the status as "active"...

how can I read correctly from DB when status is Bad?

thanks

**Comment by jonjensen** [comment] 2023-03-09 15:01
Closing older issues that do not clearly indicate a Bucardo bug we can act on. If you can show a reproduceable problem on the current version of Bucardo, please share.

**Closed by jonjensen** 2023-03-09 15:01 UTC
